### ISSUE TITLE
Add default icon for unknown platforms

### ISSUE THREAD

**Issue by pfefferle** [stefanbohacek/fediverse-share-button-wordpress#2]
See WordPress for example:

<img width="538" alt="Screenshot 2024-07-28 at 14 46 19" src="https://github.com/user-attachments/assets/4fa2cffe-959b-4c1c-b009-9eb72b2900cb">

**Comment by pfefferle** [comment]
On possibility is to use the `nodeIcon` from the nodeinfo endpoint!?!

https://notiz.blog/wp-api/nodeinfo/2.1

**Comment by stefanbohacek** [comment]
This is now fixed, thank you!

![Screenshot of the sharing prompt with notiz.blog used as the server name with a note: This server does not support sharing. Please visit notiz.blog.](https://github.com/user-attachments/assets/f113f13b-f16c-41a0-a7e0-d35ddf332eaf)
